(function(z){
'use strict';var q$=function(a){z.C.call(this);this.C(a)},QCa=function(a,b){b=b.g();if(b===Number||b.$isProtoEnum)return a=Number(a),Number.isNaN(a)?void 0:a;if(b===Boolean)return!!a;if(b===String)return String(a)},RCa=function(a,b){this.user=a;this.quotes=b},r$=function(a){return a.aA.best||null},s$=function(){this.nz=1},t$=function(a){z.Ak.call(this);this.C(a)},u$=function(a,b){b=b.filter(function(a){return"anon"!=a.Wa()});b=z.Za(b,function(a){return a.Wa()},a);return z.cb(b).map(function(a){return new RCa(a[0].Wb(),
a)},a)},SCa=function(a,b,c,d){return(0,z.dd)(a.Pp[b.name]||[],function(a){return a.xc()==c&&a.rd()==d})},TCa=function(a,b){return z.B(a,"slots",b)},UCa=function(a,b){return z.B(a,"requestContext",b)},v$=function(a){z.C.call(this);this.C(a)},w$=function(a){return z.A(a,"inResponseToMediaResource")},x$=function(a){return z.A(a,"mediumQuote")},VCa=function(a,b){a.gF=b;return a},y$=function(a,b){return r$(a)?z.bI(r$(a)).filter(function(a){return this.$P(a)==b},a):[]},WCa=function(a,b,c){var d=a.o.F(z.iP,
{postId:b},{filter:c});return z.CL(a,d,function(){return this.Xa.io(d)})},XCa=function(a,b){var c=a.o.F(z.zO,{postId:b});return z.CL(a,c,function(){return this.Xa.io(c)})},YCa=function(a){z.KC(a.sa,z.mn("",a.ho()))},ZCa=function(a,b,c){c=c.Lt;b=b.getAttribute("name").split(" ");var d=z.ob(b);a=(a.Pp[c.name]||[]).filter(function(a){return d[a.Wg()]});return a.length?z.gI(a):null},$Ca=function(a,b,c,d){b=SCa(a,b,c,d);return u$(a,b)},aDa=function(a,b){var c=0;(a.Pp[b]||[]).forEach(function(a){"anon"==
a.Wa()&&(c+=a.wd())});return c},bDa=function(a,b){z.Sp(a,7);var c=new z.Jp("",1,a.la());b.forEach(function(a){z.Qp(c,z.yp(a.startOffset,a.endOffset,[a.quoteId],[a.userId]))},a);b=z.Wp(c);for(var d=z.Xp(c,b),e=0;e<b.length;e++){var g=d[e];if(g.length){for(var h={},l=[],p=0;p<g.length;p++){var r=g[p];h[z.A(r,"creatorIds")]=!0;l.push(r.getName())}g=b[e];p=e<b.length-1?b[e+1]:a.la().length;z.Qp(a,z.yp(g,p,l,Object.keys(h)))}}},cDa=function(a,b,c){b="";a.oja?a=z.n("Top highlight"):(c=""+z.E(z.lV(z.F(a,
{bR:!0,J3:!c.useragent.isMobile}),c)),1==a.Eg&&a.isActive&&(a=z.n("highlighted"),c+=" "+a),a=(0,z.D)(c));b+=a;return(0,z.D)(b)},z$=function(a,b){this.pg=a;this.I8=b;this.Ad=(this.Ki=b=z.FE(a.node,b))&&b.getAttribute("name");this.TE=b?z.Qv(a,b):-1},dDa=function(a,b,c){return(0,z.D)(z.JU(z.F(a,{user:c.currentUser,type:"quoteResponses"}),c))},eDa=function(a,b,c){return(0,z.D)('\x3cdiv\x3e\x3cdiv class\x3d"buttonSet buttonSet--highlightMenu"\x3e'+z.E(z.Ay({action:"quote",source:"quote_popover",icon:(0,z.N)(""+
z.E(z.Sx())),s:"button--highlightMenu u-accentColor--highlightStrong js-quoteAttributions-pileOn",Xb:!0,uj:!0,QO:"quote",ca:!0,isActive:a.isActive},c))+(c.supportsEdit?z.E(z.Ay({action:"quote-respond",source:"quote_popover",icon:(0,z.N)(""+z.E(z.$x())),s:"button--highlightMenu",Xb:!0,ca:!0},c)):"")+(a.XI?z.E(z.Ay({action:"twitter",source:"quote_popover",icon:(0,z.N)(""+z.E(z.dy())),s:"button--highlightMenu",Xb:!0,ca:!0},c)):"")+'\x3cdiv class\x3d"buttonSet-separator"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"js-quoteAttributions-info quoteAttributions-info"\x3e'+
cDa(a,0,c)+"\x3c/div\x3e\x3c/div\x3e")},A$=function(a){z.Kd.call(this);var b=z.xi();this.fi=b&&new z$(z.wj(b,!0),a);this.Kj=b&&new z$(z.wj(b,!1),a)},fDa=function(){var a=z.n("Highlights");return(0,z.D)(""+a)},B$=function(a,b,c){z.U.call(this);this.od=a.get("quotes-data");var d=this.od.dm;d.subscribe("add",this.lY,this);d.subscribe("remove",this.lY,this);this.Ga=b;this.ld=b.Ij;this.Vk=c;this.jV=[];this.sa=a.get("app");this.ka=a.get("popover");this.o=a.get("route-builder");this.tL=a.get("global-event-bus");
this.qda=a.get("progressive-media-loader")},hDa=function(a,b,c,d){var e=gDa(a,b);if(e){var g=a.Ga.isPublished(),h=z.FI(a.Ga);e.XI=g&&h;if(c=z.nG(z.pG(z.qG(z.mG(z.oG(z.lG(a.ka).La(eDa,e),"top"),c),{RH:!0,EB:!0}),"popover--dark popover--quoteAttributions"),d).S())c.xk("deactivate",function(){this.lm===b&&C$(this,null)},a),c.Gm().D("quote",a.B9.bind(a,c)).D("quote-respond",a.C9.bind(a,c)).D("twitter",a.D9.bind(a))}},gDa=function(a,b){if("anon"==b.Wa())return{isActive:!1,oja:!0};var c=D$(a,b),d=b.xc();
b=b.rd();a=$Ca(a.od,c,d,b);if(!a||!a.length)return null;a=(0,z.pb)(a,function(a){return a.user});c=(0,z.dd)(a,function(a){return a.userId!=z.ym().userId});return{isActive:(0,z.Nc)(a,function(a){return a.userId==z.ym().userId}),social:c,Eg:a.length}},iDa=function(a,b){a=a.ld.querySelectorAll('.markup--quote[name~\x3d"'+b.Wg()+'"]');return z.Ra(a)},D$=function(a,b){b=b.Fb()[0].name;return(b=z.kp(a.ld,b))?a.Ga.Vg(b):null},jDa=function(a,b){var c=z.yi(b);return(c=z.rI(a.Vk,c))?ZCa(a.od,b,c):null},C$=
function(a,b){a.lm!==b&&(a.lm&&kDa(a,a.lm,!1),b&&kDa(a,b,!0),a.lm=b)},kDa=function(a,b,c){iDa(a,b).map(function(a){z.gd(a,"is-targeted",c)})},E$=function(a,b){(b=lDa(a,b))&&z.pI(a.pi(),b)},lDa=function(a,b){var c=b.Fb(),d=z.kp(a.ld,c[0].getName());a=z.kp(a.ld,z.Ga(c).getName());return z.PH(d,b.xc(),a,b.rd())},F$=function(a,b,c,d){a={postId:a.Ga.ua(),quoteId:b,source:d};z.ix(c?z.sI:z.fma,a)},mDa=function(a,b){z.IE(a,z.HE,z.Gb(b,z.Db(!0)),void 0)},G$=function(a){z.yw.call(this);this.Db=a.get("dom-model-converter");
this.nX={};this.kW={};this.XM={};this.X=a;this.em=a.get("request");this.o=a.get("route-builder");this.aa=a.get("model-store");this.Fa="";this.MX=0;this.hV=!1;this.Rl=null},H$=function(a,b){var c=a.nX[b];c||(c=a.nX[b]=new z.WH,a.ba("new_note_list",c,a));return c},nDa=function(a,b){if(!b)return!1;var c=b.la();if(a.content==c.substring(a.startIndex,a.endIndex))return!0;var d=new RegExp(z.ya(a.content),"gi"),c=(b=d.exec(c))&&d.exec(c);return b&&!c?(c=a.endIndex-a.startIndex,a.startIndex=b.index,a.endIndex=
b.index+c,a.content=b[0],!0):!1},I$=function(a,b,c){var d=b.ua(),e=b.gf(),g=H$(a,b.Oc()),h=g?g.indexOf(b):-1,l=b.lB();b.vu(c);"HIDDEN"==c?a.aa.remove(b):b=z.FH(a.aa,b);var p=g?g.indexOf(b):-1;return{dj:a.em.put(a.o.F(z.vka,{postId:d,noteId:e}),{state:c}),cC:function(){b.vu(l);-1==p&&(-1==h?g.add(b):z.ZH(g,b,h))}}},J$=function(a,b,c,d,e,g){var h=z.A(a.Fm(c,e),"replies"),l=z.Ha(h,function(a){return a.Et()==b}),p=h[l];"HIDDEN"==g&&z.Ma(h,l);c=a.o.F(z.yka,{postId:d,noteId:c,replyId:b});a=a.em.put(c,{state:g});
var r=z.Ha(h,function(a){return a.Et()==b});return{dj:a,cC:function(){-1==r&&z.Ua(h,l,0,p)}}},oDa=function(a,b,c){this.range=a;this.anchor=b;this.at=b.getAttribute("name");this.highlight=c},K$=function(a,b,c){z.U.call(this);this.xF=b;this.fda=c;this.Aa=a.get("screen");this.ya=a.get("screen-request")},pDa=function(a,b){b=b.querySelectorAll(".js-trackedPostPromotion");null!=a.xF.postPageContext&&null!=a.xF.postPageContext.postId&&z.Ra(b).forEach(function(b){var d=a.xF.postPageContext.postId,e=b.getAttribute("data-post-id"),
g=b.getAttribute("data-post-promotion-source");b=b.getAttribute("data-location-id");z.ix(z.xI,{hostPostId:d,targetPostId:e,promotionSource:g,locationId:b})})},qDa=function(a,b,c){return(0,z.D)('\x3cdiv class\x3d"postBundle"\x3e\x3cdiv class\x3d"container u-maxWidth740"\x3e\x3cdiv class\x3d"supplementalPostContent relatedReadsStream js-relatedReadsStream u-maxWidth640"\x3e'+z.E(z.IV(a,0,c))+"\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e")},L$=function(a){z.U.call(this);this.fa=null;this.ya=a.get("screen-request");
this.X=a},rDa=function(){},sDa=function(a){this.SE=a},M$=function(a,b){return b?z.kp(a.SE,b):null},tDa=function(a,b,c){mDa(a.SE,function(a){var e=a.getAttribute("name");e&&b.call(c,a,e)})},uDa=function(a,b){return z.og(a.SE,b)?a.SE:null},N$=function(a,b,c,d,e){z.r1.call(this,a,b);this.Ia(new z.y0(c));this.Ia(new z.X1(!1));this.Ia(new z.Z1(a));this.Ia(new z.s1);this.Ia(new z.b2(!1));this.Ia(new z.e2(d,!0));this.Lg=!0;this.Rj=d;this.em=a.get("request");this.ga=a.get("dialog");this.EM=e;this.S()},vDa=
function(){var a=z.n("Saving failed. You may be having connectivity issues or notes might be disabled on this post. Please try again.");return(0,z.D)(""+a)},wDa=function(){var a=z.n("Yikes! Something happened and we couldn’t dismiss this note.");return(0,z.D)(""+a)},xDa=function(){var a=z.n("Yikes! Something happened and we couldn’t delete this note.");return(0,z.D)(""+a)},yDa=function(){var a=z.n("Yikes! Something happened and we couldn’t delete this reply.");return(0,z.D)(""+a)},zDa=function(){var a=
z.n("The note has been dismissed.");return(0,z.D)(""+a)},ADa=function(){var a=z.n("The note has been deleted.");return(0,z.D)(""+a)},BDa=function(){var a=z.n("The reply has been deleted.");return(0,z.D)(""+a)},CDa=function(){var a=z.n("Write a note…");return(0,z.D)(""+a)},DDa=function(){var a=z.n("Cancel");return(0,z.D)(""+a)},O$=function(a,b,c,d,e){N$.call(this,a,b,e||"Leave a note",400,d||null);this.Fa=c;this.o=a.get("route-builder");this.he=a.get("notes-data")},P$=function(a,b,c,d,e,g){N$.call(this,
a,b,"Leave a reply…",200,d);this.o=a.get("route-builder");this.he=a.get("notes-data");this.Fa=c;this.hY=g||null;this.Ad=e},FDa=function(a,b,c){var d='\x3cdiv class\x3d"quoteResponses js-quoteResponses"\x3e',e=a.quotes.length,g=a.responses.length||a.CT;b=a.notes.length||a.UI;if(e||g||b){if(e){var e='\x3cdiv class\x3d"quoteResponses-section"\x3e'+z.E(z.rA({title:(0,z.N)(z.E(fDa())+" ("+z.E(a.quotes.length)+")"),pe:!0},c)),h;h={W2:a.quotes,Wma:!0};var l='\x3cdiv class\x3d"js-quotesList"\x3e';if(!h.Wma)var p=
z.n("Learn more"),l=l+z.E(z.rA({title:(0,z.N)(""+z.E(fDa())),pe:!0,Ic:(0,z.N)(""+z.E(z.pA({href:(0,z.L)(""+z.J((0,z.jq)("https://medium.com/the-story/introducing-highlights-a4df69e8ed43"))),moreText:(0,z.N)(""+p),Ab:!0},c)))},c));for(var p="list list--quotes list--short"+(h.W2.length?"":" is-empty"),p=(0,z.N)(p),l=l+('\x3cul class\x3d"'+z.H(p)+'"\x3e'),p=h.W2,r=p.length,u=0;u<r;u++){for(var x=p[u],I="",M=x.quotes,R=M.length,P=0;P<R;P++)I+=""+M[P].quoteId+(P!=R-1?",":"");I=z.G(I);l+='\x3cli class\x3d"list-item list-item--inline" data-quote-ids\x3d"'+
z.H(I)+'" data-quote-creator-id\x3d"'+z.H(x.user.userId)+'" data-action\x3d"highlight-quote" data-action-type\x3d"hover"\x3e'+z.E(z.Jz(z.F(h,{user:x.user,Fl:!0}),c))+"\x3c/li\x3e"}h=(0,z.D)(l+"\x3c/ul\x3e\x3c/div\x3e");e=e+z.E(h)+"\x3c/div\x3e"}else e="";g?(g='\x3cdiv class\x3d"quoteResponses-section'+(a.CT?" is-withEditor":"")+'"\x3e'+z.E(z.rA({title:(0,z.N)(""+z.E(z.Ry())),pe:!0},c)),a.CT&&c.supportsEdit&&c.isAuthenticated?(h={},h=(0,z.D)('\x3cdiv class\x3d"js-inlineNewPostControl inlineNewPostControl inlineNewPostControl--quoteResponses blockGroup blockGroup-list"\x3e'+
z.JU(z.F(h,{user:c.currentUser,isCollapsed:!0,Wt:!0,type:"quoteResponses",ir:(0,z.N)(""+z.E(z.Zy()))}),c)+"\x3c/div\x3e"),h=z.E(h)):h="",g=g+h+EDa(a,0,c)+"\x3c/div\x3e"):g="";d+=e+g;if(a.Vka&&b){g=z.n("Who can see this?");d+='\x3cdiv class\x3d"quoteResponses-section quoteResponses-section--fullBleed u-paddingLeft0 u-paddingRight0"\x3e';b="";e=a.post.homeCollection;e=""+("Private notes are visible to you"+(a.post.creator.userId!=c.currentUser.userId?", the author,":"")+" and the editors of "+(e?z.E(e.name):
"any publication this story is added\x26nbsp;to")+".");e=(0,z.D)(e);e=""+z.E(e);e=(0,z.N)(e);b+='\x3cspan data-tooltip\x3d"'+z.H(e)+'"\x3e'+g+"\x3c/span\x3e";g={};g=(0,z.D)(z.Dx(z.F(g,{name:"lock",size:"19px",content:(0,z.N)('\x3csvg class\x3d"svgIcon-use" width\x3d"19" height\x3d"19" viewBox\x3d"0 0 19 19" \x3e\x3cpath d\x3d"M14 14.052a1 1 0 0 1-.992.998H5.992A.99.99 0 0 1 5 14.052v-4.004a1 1 0 0 1 .992-.998h7.016a.99.99 0 0 1 .992.998v4.004zM7 5.445C7 4.187 8.114 3.15 9.5 3.15c1.385 0 2.5 1.04 2.5 2.295V8.05H7V5.445zm6.008 2.605H13V5.445c0-1.822-1.578-3.295-3.5-3.295C7.577 2.15 6 3.618 6 5.445V8.05h-.008A2 2 0 0 0 4 10.048v4.004a1.99 1.99 0 0 0 1.992 1.998h7.016A2 2 0 0 0 15 14.052v-4.004a1.99 1.99 0 0 0-1.992-1.998z" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')})));
g=(0,z.N)(""+z.E(g));e=z.n("Private notes");e=(0,z.D)(""+e);b={pT:g,title:(0,z.N)(""+z.E(e)),pe:!0,Ic:(0,z.N)(b),s:"heading--privateNotes"};b=(0,z.D)(z.nA(z.F(b,{Pg:(0,z.N)(""+z.oA(b,c)),Rja:!0})));b=d+=z.E(b);d=""+('\x3cdiv class\x3d"privateNotes-list js-notesList'+(a.UI?" is-showingNoteEditor":"")+(0==a.notes.length?" is-empty":"")+'"\x3e');g=a.notes;e=g.length;for(h=0;h<e;h++)d+=Q$({note:g[h],post:a.post,uC:a.uC},0,c);a.UI?(g=a.post.creator,a="",g=c.currentUser.userId==g.userId?z.n("Leave yourself a note"):
z.n("Send {$name} a private note…",{name:z.E(g.name)}),a+=g,a=(0,z.D)(a),a='\x3cdiv class\x3d"privateNotes-actions js-noteActions"\x3e'+z.E(z.xy({action:"show-note-editor",text:(0,z.N)(""+z.E(a)),s:"privateNotes-prompt"},0,c)),g=z.D,e='\x3cdiv class\x3d"privateNotes-editor"\x3e'+z.E(z.iA({user:c.currentUser,me:!0},c))+'\x3cdiv class\x3d"js-noteEditor"\x3e\x3c/div\x3e\x3cdiv class\x3d"buttonSet"\x3e',h=z.n("Send"),h=(0,z.D)(""+h),c=g(e+z.E(z.xy({action:"save-note",isPrimary:!0,s:"js-saveNoteButton",
text:(0,z.N)(""+z.E(h))},0,c))+z.E(z.xy({action:"hide-note-editor",text:(0,z.N)(""+z.E(DDa()))},0,c))+"\x3c/div\x3e\x3c/div\x3e"),c=a+c+"\x3c/div\x3e"):c="";c=(0,z.D)(d+("\x3c/div\x3e"+c));d=b+('\x3cdiv class\x3d"quoteResponses-inner privateNotes"\x3e'+c+"\x3c/div\x3e\x3c/div\x3e")}}else 0<a.$x&&(a=z.n("Show previous tip"),b=z.n("Show next tip"),d+='\x3cdiv class\x3d"quoteResponses-section quoteResponses-section--fullBleed quoteResponses-section--tips u-textAlignCenter u-paddingLeft0 u-paddingRight0"\x3e\x3cdiv class\x3d"quoteResponses-section--tipsInner u-alignMiddle"\x3e'+
z.E(z.Ay({Kb:!0,oe:!0,ca:!0,action:"previous-highlight-tip",icon:(0,z.N)(""+z.E(z.Hx())),title:(0,z.N)(""+a)},c))+"\x3cdiv class\x3d'u-alignBlock quoteResponses-section--tipsContent u-paddingLeft20 u-paddingRight20 js-highlightTip'\x3e\x3c/div\x3e"+z.E(z.Ay({Kb:!0,oe:!0,ca:!0,action:"next-highlight-tip",icon:(0,z.N)(""+z.E(z.Jx())),title:(0,z.N)(""+b)},c))+"\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");return(0,z.D)(d+"\x3c/div\x3e")},EDa=function(a,b,c){return(0,z.D)(z.E(z.yV({source:"quoteResponses",count:a.responses.length,
posts:a.responses,tc:!0,Yc:!0,Lh:!0,UQ:!0,hka:!0,$e:!0,I0:!0},c)))},Q$=function(a,b,c){var d,e=null==a.note.replies?null:a.note.replies.length,g=null==a.note.replyId,h=a.post.creator.userId==c.currentUser.userId,l=a.post.creator.userId==a.note.author.userId;d=a.note.author.userId==c.currentUser.userId;b=h||(null==a.post.homeCollection?null:a.post.homeCollection.virtuals.permissions.canEditPosts);var p=""+(g?"js-note-item"+(a.note.noteId?" js-note-"+a.note.noteId:""):"js-reply-item"+(a.note.replyId?
" js-reply-"+a.note.replyId:"")),p=z.G(p),p='\x3cdiv class\x3d"privateNotes-item '+z.H(p)+' js-note" data-note-id\x3d"'+z.H(a.note.noteId)+'"\x3e'+(g?z.E(z.Jz({user:a.note.author},c)):z.E(z.Hz({user:a.note.author},c)))+'\x3cdiv class\x3d"privateNotes-authorLockup"\x3e\x3cdiv class\x3d"privateNotes-author"\x3e'+z.E(z.Hy({user:a.note.author},c));g||!(h||d||(null==a.post.homeCollection?0:a.post.homeCollection.virtuals.permissions.canEditPosts))||l||a.y1?h="":(h=z.n("(Editor)"),h=(0,z.D)(""+h),h='\x3cspan class\x3d"privateNotes-author--supplemental"\x3e '+
z.E(h)+"\x3c/span\x3e");p=p+h+'\x3c/div\x3e\x3cdiv class\x3d"privateNotes-supplemental"\x3e'+z.E(z.Jj(Number(a.note.createdAt),c))+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"privateNotes-content js-privateNotesContent"\x3e';h=z.E(z.Ls(String(a.note.content),c));l=String(h).replace(/(\r\n|\r|\n)/g,"\x3cbr\x3e");h=z.wn(h,z.zn)?(0,z.D)(l,z.xn(h)):l;d=""+(p+h+"\x3c/div\x3e"+(d?GDa({note:a.note,isPrimary:g},c):""));if(g){d+='\x3cdiv class\x3d"privateNotes-replies'+(e?"":" is-empty")+' js-repliesList"\x3e';
if(e)for(e=a.note.replies,g=e.length,p=0;p<g;p++)h=e[p],d+=Q$({note:h,post:a.post,y1:a.note.author.userId==h.author.userId},0,c);e=d;a.uC?(g=z.D,d='\x3cdiv class\x3d"privateNotes-editor privateNotes-editor--reply"\x3e'+z.E(z.Iz({user:c.currentUser,me:!0},c))+'\x3cdiv class\x3d"js-replyEditor"\x3e\x3c/div\x3e\x3cdiv class\x3d"buttonSet"\x3e',p=z.n("Send"),p=(0,z.D)(""+p),g=g(d+z.E(z.xy({action:"save-reply",isPrimary:!0,text:(0,z.N)(""+z.E(p))},0,c))+z.E(z.xy({action:"hide-reply-editor",text:(0,z.N)(""+
z.E(DDa()))},0,c))+"\x3c/div\x3e\x3c/div\x3e")):g="";g="\x3c/div\x3e"+g+'\x3cdiv class\x3d"privateNotes-actions'+(b?" privateNotes-actions--withDismiss":"")+' u-clearfix"\x3e';a.uC?(d=z.D,p=z.n("Reply"),p=(0,z.D)(""+p),d='\x3cdiv class\x3d"u-floatLeft"\x3e'+d(z.E(z.xy({isPrimary:!0,action:"show-reply-editor",s:"privateNotes-prompt",text:(0,z.N)(""+z.E(p))},0,c)))+"\x3c/div\x3e"):d="";d=e+(g+d+(b?'\x3cdiv class\x3d"u-floatRight"\x3e'+GDa({note:a.note,isPrimary:!0,d1:!0},c)+"\x3c/div\x3e":"")+"\x3c/div\x3e")}return(0,z.D)(d+
"\x3c/div\x3e")},GDa=function(a,b){var c=z.D,d=a.isPrimary?a.note.noteId:a.note.replyId,e=a.d1?"dismiss-note":a.isPrimary?"delete-note":"delete-reply";a=a.d1?z.n("Dismiss note"):z.n("Delete");a=(0,z.D)(""+a);a=z.E(a);return c(z.E(z.xy({actionValue:d,action:e,s:"privateNotes-delete js-deleteNote",text:(0,z.N)(""+a)},0,b)))},HDa=function(a,b,c){b="";if(0==a.Bf)a=1==a.$x?z.n("People highlighted this passage. You can click on an existing highlight to add to it, like below:"):z.n("{$topQuoteCount} people highlighted this passage. You can click on an existing highlight to add to it, like below:",
{topQuoteCount:z.E(a.$x)}),b+=a,b+='\x3cimg class\x3d"quoteResponses-tipAnimation" src\x3d"'+z.H(z.qo(z.Ms("/img/help/highlight-tips-2.gif",c.fp)))+'"\x3e';else if(1==a.Bf)a=z.n("Or, select any passage to create your own highlight and tell the author and others what resonated with you:"),b+=a+'\x3cimg class\x3d"quoteResponses-tipAnimation" src\x3d"'+z.H(z.qo(z.Ms("/img/help/highlight-tips-1.gif",c.fp)))+'"\x3e';else if(2==a.Bf){a=z.n("Sign in to create a profile");var d=z.n("so that you can save your highlights and share them with others.");
b+=z.E(z.W({uc:!0,Xb:!0,source:"highlight_tip",w:(0,z.N)(""+a),href:(0,z.L)(""+z.J(z.qq(c)))},c))+" "+d}return(0,z.D)(b)},R$=function(a,b,c,d,e,g,h,l){z.U.call(this);this.X=a;this.ea=a.get("butter-bar");this.Ga=b;this.Ad=c;this.$h=e;this.od=a.get("quotes-data");this.he=a.get("notes-data");this.vh=a.get("responses-data");this.Qd=g;this.EM=d;this.qN=(this.Tz=h)?h.Wg():null;this.xe=this.Nc=null;this.di={};this.vW=!!z.Am();this.xW=!!z.Cm();this.xv=this.vW&&this.xW&&z.DI(b);this.wn=null;this.kE=0;this.bZ=
aDa(this.od,this.Ad);this.rs=l;this.Na(this.uK())},IDa=function(a){a.ub(".js-block").forEach(function(a){this.qa(a,"mouseenter",this.d$,this);this.qa(a,"mouseleave",this.rO,this)},a)},JDa=function(a){a.ub(".js-note").forEach(function(a){this.qa(a,"mouseenter",this.b$,this);this.qa(a,"mouseleave",this.rO,this)},a)},KDa=function(a,b){var c=a.query(".js-note-"+b);a.di[b]||(a.di[b]=new P$(a.X,c.querySelector(".js-replyEditor"),a.Ga.ua(),b,a.Ad),z.Bw(a,a.di[b],"saving",a.aca,a),z.Bw(a,a.di[b],"save",a.Wba,
a),z.Bw(a,a.di[b],"fail",a.fba,a));z.w(c,"is-noteEditorVisible");a.di[b].focus()},LDa=function(a,b){var c=a.di[b];c&&(c.Ha()&&c.Zc(""),a=a.query(".js-note-"+b),z.ed(a,"is-noteEditorVisible"))},MDa=function(a,b,c){var d=M$(a.Qd,a.Ad);if(d){var e=[];a.rs&&(e=a.rs.quotes.map(function(a){return a.Wg()}));(0,z.pb)(d.querySelectorAll(".markup--quote"),function(a){var d=a.getAttribute("data-creator-ids").split(" "),d=z.La(d,b);if(this.rs)var l=a.getAttribute("name").split(" "),d=d&&(0,z.Nc)(l,z.La.bind(null,
e));z.gd(a,"is-selected",c&&d)},a)}},S$=function(a){return(a=z.gp(a,function(a){return z.bd(a,"js-note-item")}))&&a.getAttribute("data-note-id")},NDa=function(a,b,c,d){b=new z.YF(b,300);b.Na(c);b.subscribe("dismiss",d,a);b.S();return b},T$=function(a){var b=a.Fb(),c=a.xc();a=a.rd();1<b.length&&(a=b[0].la().length);var d=new z.us;d.cn(b[0].getName());d.Af(c);z.B(d,"endIndex",a);d.Zc(b[0].la().substring(c,a));return d},U$=function(a,b){b%=3;0>b&&(b=2);a.kE=b;(b=a.query(".js-highlightTip"))&&z.S(b,HDa,
{Bf:a.kE,$x:a.bZ})},V$=function(a,b,c,d){z.U.call(this);this.Na(this.uK(d));this.$a=a.get("dom-monitor");this.Ga=b;this.BW=!b.Ma().Eq()||b.Qc();this.Fa=b.ua();this.Qd=c;this.od=a.get("quotes-data");this.vh=a.get("responses-data");this.he=a.get("notes-data");this.Wr=null;this.Zf={}},ODa=function(a,b){b.forEach(function(a){a&&W$(this,a)},a)},W$=function(a,b){if(!a.Wr)if(M$(a.Qd,b)){var c=PDa(a,b),c=QDa(a,c),c=RDa(a,c),c=SDa(a,c);a.Zf[b]=c;TDa(a,b)}else delete a.Zf[b]},UDa=function(a,b){if(!a.Wr){var c=
a.Zf[b];if(c){var d=c.length,c=RDa(a,c),c=SDa(a,c);a.Zf[b]=c;d!=c.length?TDa(a,b):c.forEach(function(a){a.wa&&a.offsetTop&&(a.wa.style.top=a.offsetTop+"px")})}}},VDa=function(a,b,c){return z.Ia(a.Zf[b]||[],function(a){return a.wa==c})},PDa=function(a,b){var c=[];H$(a.he,b).tf(function(a){var e=a.Rw(),g;e?(g=this.he.fH(e),e=g.Pa(),g=z.A(g,"endIndex")):(e=0,g=a.Ha().length);c.push({anchor:b,startIndex:e,endIndex:g,notes:[a],quotes:[],responses:[]})},a);if(a.BW)return c;(a.od.Pp[b]||[]).forEach(function(a){var e=
WDa(a);c.push({anchor:b,startIndex:e.startIndex,endIndex:e.endIndex,notes:[],quotes:[a],responses:[]})},a);y$(a.vh,b).forEach(function(a){var e=w$(a);e&&(e=x$(e)&&x$(e).ol())&&(e=WDa(e),c.push({anchor:b,startIndex:e.startIndex,endIndex:e.endIndex,notes:[],quotes:[],responses:[a]}))},a);return c},QDa=function(a,b){var c=[];b.sort(function(a,b){return a.startIndex-b.startIndex});b.forEach(function(a){var b=z.Ha(c,function(b){return b.endIndex>=a.startIndex-1&&b.startIndex<=a.endIndex+1});0<=b?this.sz(c[b],
a):c.push(a)},a);return c},SDa=function(a,b){var c=[];b.forEach(function(a){if(a.offsetTop){var b=z.Ha(c,function(b){return 30>=Math.abs(b.offsetTop-a.offsetTop)});0<=b?this.sz(c[b],a):c.push(a)}},a);return c},TDa=function(a,b){a.ub(".js-paragraphControl-"+b).forEach(z.ig);a.Zf[b]=a.Zf[b].map(function(a){var b=XDa(this,a),b=z.lv(YDa,b);b.style.top=a.offsetTop+"px";a.wa=b;this.W().appendChild(a.wa);z.w(b,"is-visible");return a},a)},XDa=function(a,b){var c=b.notes,d=b.responses,e=u$(a.od,b.quotes),
g=d?d.length:0,h=c?c.length:0,l=0,p=0,r=0,u=!1,x=!1,I={},M={},R=z.ym().userId,P=a.Ga.Ma().Ce().Wa();c.forEach(function(a){var b=a.dB();b&&((a=z.A(a,"replies"))&&a.forEach(function(a){h++;a.author&&(a.author.userId==R&&l++,a.author.social&&a.author.social.isFollowing&&(I[a.author.userId]=a.author),M[a.author.userId]=!0)}),M[b.userId]=!0,b.userId==R&&l++,b.userId==P?p++:r++,b.social&&b.social.isFollowing&&(I[b.userId]=b))});e.forEach(function(a){a=a.user;M[a.userId]=!0;a.userId==R&&(u=!0);a.social&&
a.social.isFollowing&&(I[a.userId]=a)});d.forEach(function(a){a=a.Ce();M[a.userId]=!0;a.userId==R&&(x=!0);a.social&&a.social.isFollowing&&(I[a.userId]=a)});c=b.quotes.filter(function(a){return"anon"==a.Wa()});return{postId:a.Fa,at:b.anchor,Tka:h,Bla:g,ku:x,bu:l,x2:p,Uka:r,Bya:e.length,hu:u,Y0:Object.keys(M).length,fja:z.cb(I),$x:c.length}},WDa=function(a){var b=a.xc(),c=a.rd();1<a.paragraphs.length&&(c=a.paragraphs[0].text.length);return{startIndex:b,endIndex:c}},RDa=function(a,b){var c=z.Lv();return b.map(function(a){var b=
this.Qd.get(a.anchor),g=this.Ga.Vg(b);if(!g)return a;var h;4==g.type&&(g.la()&&(h=b.querySelector("figcaption")),h||(h=b));if(!h){g=a.startIndex+1;b=[b];h=0;for(var l=null;0<b.length&&h<g;)if(l=b.pop(),!(l.nodeName in z.eW))if(3==l.nodeType){var p=l.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");h+=p.length}else if(l.nodeName in z.fW)h+=z.fW[l.nodeName].length;else for(p=l.childNodes.length-1;0<=p;p--)b.push(l.childNodes[p]);h=l}g=z.Pv(h,!0);a.offsetTop=Math.round(g.top+c.top);return a},
a)},YDa=function(a,b,c){b=z.D;var d='\x3cdiv class\x3d"paragraphControls js-paragraphControl js-paragraphControl-'+z.H(a.at)+' u-noUserSelect"\x3e',e=z.D,g;if(a.Tka||a.Bla){g='\x3cdiv class\x3d"notesMarker u-noUserSelect" data-action\x3d"select-anchor" data-action-value\x3d"'+z.H(a.at)+'"\x3e';var h;h={};h=(0,z.D)(z.Dx(z.F(h,{name:"asteriskFilled",size:"19px",content:(0,z.N)('\x3csvg class\x3d"svgIcon-use" width\x3d"19" height\x3d"19" viewBox\x3d"0 0 19 19" \x3e\x3cpath d\x3d"M14.78 8.07a8.681 8.681 0 0 0-.427-1.383.478.478 0 0 0-.584-.27l-3.12.77V4.034c0-.247-.19-.48-.43-.5a7.23 7.23 0 0 0-1.38 0c-.24.02-.43.253-.43.5V7.19L5.3 6.415a.48.48 0 0 0-.583.27c-.18.448-.324.91-.426 1.383-.05.24.1.5.32.58l3.06.754-1.98 2.956c-.14.196-.13.502.04.67.34.332.7.632 1.09.896.2.136.49.077.63-.117l2.09-3.114 2.09 3.112c.15.193.43.252.63.116.39-.26.75-.56 1.09-.89.17-.17.19-.47.04-.67L11.4 9.41l3.06-.76a.517.517 0 0 0 .32-.58" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')})));
g=g+z.E(h)+"\x3c/div\x3e"}else g="";var l;h=""+(1==a.bu?"a note":"notes");h=z.G(h);l=""+(1==a.Y0&&(0<a.bu||a.hu||a.ku)?0<a.bu&&a.hu&&a.ku?" highlighted, responded, and left "+h:0<a.bu&&a.ku?" responded and left "+h:0<a.bu&&a.hu?" highlighted and left "+h:a.hu&&a.ku?" highlighted and responded":a.hu?" highlighted":0<a.bu?" left "+h:a.ku?" responded":"":"");l=z.G(l);h='\x3cspan class\x3d"paragraphControls-itemText"\x3e';c=""+(0<a.x2&&0==a.Uka&&!a.hu&&!a.ku?1==a.x2?"Note to self":"Notes to self":z.E(z.lV(z.F(a,
{social:a.fja,isActive:0<a.bu||a.hu||a.ku,Eg:a.Y0,bR:!0,bla:!0,p_:0<a.$x?"Top highlight":""}),c))+z.E(l));c=(0,z.N)(c);h+=z.E(z.jU(z.F(a,{text:c})))+"\x3c/span\x3e";a=(0,z.D)(h);a=e(g+a);return b(d+a+"\x3c/div\x3e")},X$=function(a,b,c){z.U.call(this);this.X=a;this.L8=a.get("floating-components");this.Aa=a.get("screen");this.Oa=a.get("screen-service");this.Ah=a.get("uri-fragment");this.$a=a.get("dom-monitor");this.Ga=b;this.ld=b.ld;this.Ij=this.ld.querySelector(".js-postField");this.FX=this.Aa.W().querySelector(".js-notesPositionContainer");
this.od=a.get("quotes-data");this.he=a.get("notes-data");this.he.subscribe("new_note_list",this.wba,this);this.vh=a.get("responses-data");this.Gj=null;this.Qd=new sDa(this.ld.querySelector(".js-notesSource"));this.qz=this.Zf=this.CF=null;this.Zf=new V$(a,b,this.Qd,this.FX);this.track(this.Zf);this.qz=this.Zf.W();this.Hj=this.nM=null;this.Td=c},Z$=function(a,b){if(a.isActive()){var c=(b=b||a.nM)&&b.yH,d=b&&b.noteId;c&&(a.Ms(c),d&&a.he.Fm(d,c)&&a.Hj&&z.t(a.Hj,function(){Y$(this,c,null,d)},a));YCa(a.Ah)}else a.nM=
b||null},Y$=function(a,b,c,d,e,g){var h={Cg:!0,SQ:767>=window.innerWidth};a.yN();c=new R$(a.X,a.Ga,b,d||"",c||null,a.Qd,e||null,g||null);c.subscribe("set-active-highlight",a.tY,a);c.subscribe("reset-highlight",a.bea,a);c.subscribe("close",a.yN,a);b=g&&g.wa?g.wa:a.Qd.get(b);g=z.FM(a.L8);g.cl=b;b=g.Gu(c);b.sA=h;h=b.nJ(a.Yk.bind(a));h.vF=!0;a.Gj=h.S()},ZDa=function(a,b,c){var d=a.Ga.Vg(M$(a.Qd,b));if(d&&4!=d.type){z.Sp(d,4);if(c){if(!nDa(c,d))return;z.Qp(d,z.xp(c.startIndex,c.endIndex,c.id))}c=a.Ga.Qc();
var e=a.Ga.Ma();c={mode:c?"edit":"view",Jh:z.or(e),media:null,tj:null,sections:!0,rj:!1,cj:!1,Me:!1,postId:e.id};a.Qd.get(b).innerHTML=z.hs(d,z.y,c)}},$Da=function(a,b){var c=z.xi();if(!c||c.isCollapsed())if(b&&(c=b),!c||c.isCollapsed())return null;b=z.Tg(c);var d=uDa(a.Qd,b);if(!d)return null;a=(b=z.gp(b,z.HE,d))&&a.Ga.Vg(b);if(!b)return null;var d=z.Rv(c,b,!0),e=z.Rv(c,b,!1);return-1==d||-1==e?null:new oDa(c,b,new z.us({anchor:b.getAttribute("name"),startIndex:d,endIndex:e,content:a.la().substring(d,
e)}))},aEa=function(){},bEa=function(a,b,c){var d;(b=a.post.creator.userId==c.currentUser.userId&&a.post.virtuals.responsesCreatedCount>=c.l.f3)||!c.variants.enable_response_experiment_b&&!c.variants.enable_response_experiment_c?d=""+z.Ry():(d=z.n("Related Stories"),d=""+(0,z.D)(""+d));d=z.G(""+d);var e;if(c.supportsEdit)if(b)e=z.E(z.wy({pj:!0,action:"show-responses-stream-editor",s:"js-showResponsesStreamEditorButton",w:(0,z.N)(""+z.E(z.mU()))},c));else if(c.variants.enable_response_experiment_c||
c.variants.enable_response_experiment_d){e=(0,z.L)(""+z.J((0,z.jq)(z.J(z.lq(c.authBaseUrl,"NEW_RESPONSE",a.post,null,null)))));var g;c.variants.enable_response_experiment_c?(g=z.n("Write a related story"),g=(0,z.D)(""+g),g=z.E(g)):g=z.E(z.mU());e=z.E(z.W({Vd:"respond-in-full-editor",href:e,w:(0,z.N)(""+g),s:"link--accent u-accentColor--textNormal u-accentColor--textDarken u-fontSizeSmaller"},c))}else e="";else e="";d=""+('\x3cdiv class\x3d"container u-maxWidth740"\x3e\x3cdiv class\x3d"responsesStreamWrapper u-maxWidth640 u-hide js-responsesStreamWrapper"\x3e\x3cdiv class\x3d"container u-maxWidth640 responsesStream-title u-paddingTop15"\x3e\x3cdiv class\x3d"row"\x3e\x3cdiv class\x3d"col u-size12of12"\x3e'+
z.E(z.qA({title:d,KB:!0,Ic:(0,z.N)(""+e)},c))+"\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");if(c.supportsEdit){e='\x3cdiv class\x3d"container u-maxWidth640 u-marginBottom30 responsesStream-editor cardChromeless'+(b||c.variants.enable_response_experiment_a||c.variants.enable_response_experiment_b||c.variants.enable_response_experiment_c||c.variants.enable_response_experiment_d?" u-hide":"")+' js-responsesStreamEditor"\x3e\x3cdiv class\x3d"row"\x3e\x3cdiv class\x3d"col u-size12of12"\x3e';g=z.D;var h;c.isAuthenticated?
h=z.E(z.eV({ir:(0,z.N)(""+(a.post.virtuals.responsesCreatedCount?z.E(z.BW()):z.E(z.AW())))},c)):(h=a||{},h=(0,z.D)('\x3cdiv class\x3d"responses-loggedOutPrompt js-responsesLoggedOutPrompt"\x3e'+z.E(z.Ay({icon:(0,z.N)(""+z.E(z.Yx())),ca:!0,Qe:!0,Xb:!0,Wd:(0,z.L)(""+z.J(z.kq(z.F(h,{DI:!0}),0,c))),text:(0,z.N)(""+z.E(z.BW())),s:"button--loggedOutPrompt",source:"logged_out_response_prompt"},c))+"\x3c/div\x3e"));g=g(h);d+=e+g+"\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e"}b?(e='\x3cdiv class\x3d"container u-maxWidth640 u-clearfix u-paddingTop25 u-paddingBottom25 responsesManagement streamItem-card streamItem-card--hPadding20 streamItem-card--borderRadius3 cardChromeless"\x3e\x3cdiv class\x3d"u-size8of12"\x3e'+
z.E(z.HW({s:"responsesIcon u-accentColor--iconLight u-verticalAlignMiddle u-marginRight10"})),h=a.post.virtuals.responsesCreatedCount,g="",h=1==h?z.n("{$startBold}{$count}{$endBold} response to your story",{startBold:"\x3cb\x3e",count:z.E(h),endBold:"\x3c/b\x3e"}):z.n("{$startBold}{$count}{$endBold} responses to your story",{startBold:"\x3cb\x3e",count:z.E(h),endBold:"\x3c/b\x3e"}),g+=h,g=(0,z.D)(g),e=e+z.E(g)+'\x3c/div\x3e\x3cdiv class\x3d"u-size4of12"\x3e\x3cspan class\x3d"u-floatRight u-marginTop4 u-marginLeft10"\x3e',
g=(0,z.L)(""+z.J(z.QW(a,c))),h=z.n("Manage responses"),h=(0,z.D)(""+h),e=e+z.E(z.W({href:g,w:(0,z.N)(""+z.E(h)),s:"link--accent u-accentColor--textNormal u-accentColor--textDarken"},c))+"\x3c/span\x3e\x3c/div\x3e\x3c/div\x3e"):e="";if(b||!c.variants.enable_response_experiment_a&&!c.variants.enable_response_experiment_b)a="";else{g='\x3cdiv class\x3d"u-paddingTop20 u-paddingBottom25"\x3e\x3cdiv class\x3d"u-inlineBlock u-verticalAlignTop u-paddingRight10"\x3e'+z.E(z.lA({user:c.currentUser,Re:!0,me:!0},
c))+'\x3c/div\x3e\x3cdiv class\x3d"u-inlineBlock"\x3e\x3cdiv class\x3d"u-lineHeight36 u-textColorNormal u-contentSerifRegular"\x3e';if(a.post.virtuals.responsesCreatedCount){h="";var l=c.variants.enable_response_experiment_b?z.n("Write a related story…"):z.n("Write a response…")}else h="",l=c.variants.enable_response_experiment_b?z.n("Be the first to write a related story…"):z.n("Be the first to write a response…");h+=l;h=(0,z.D)(h);h=z.E(h);a='\x3cdiv class\x3d"container u-maxWidth640 u-marginBottom30 u-paddingTop5 cardChromeless"\x3e\x3cdiv class\x3d"row"\x3e\x3cdiv class\x3d"col u-size12of12"\x3e'+
z.E(z.W({Vd:"respond-in-full-editor",w:(0,z.N)(g+h+"\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e"),href:(0,z.L)(""+z.J((0,z.jq)(z.J(z.lq(c.authBaseUrl,"NEW_RESPONSE",a.post,null,null)))))},c))+"\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e"}a=e+a+'\x3cdiv class\x3d"container u-maxWidth640 u-marginBottom30 u-borderTopLighter u-hide js-noOtherResponses"\x3e\x3cdiv class\x3d"row"\x3e\x3cdiv class\x3d"col u-size12of12"\x3e\x3cdiv class\x3d"u-paddingTop20 u-paddingBottom25"\x3e\x3cdiv class\x3d"u-inlineBlock u-verticalAlignTop u-paddingRight10"\x3e'+
z.E(z.lA({Re:!0,me:!0},c))+'\x3c/div\x3e\x3cdiv class\x3d"u-inlineBlock"\x3e\x3cdiv class\x3d"u-lineHeight36 u-textColorNormal u-contentSerifRegular"\x3e';e=c.variants.enable_response_experiment_c?z.n("No related stories yet"):z.n("No responses yet");e=(0,z.D)(""+e);e=z.E(e);a=a+e+'\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"responsesStream js-responsesStream"\x3e\x3c/div\x3e\x3cdiv class\x3d"container u-maxWidth640 u-hide js-showOtherResponses"\x3e\x3cdiv class\x3d"row"\x3e';
b=b||!c.variants.enable_response_experiment_b&&!c.variants.enable_response_experiment_c?z.n("Show all responses"):z.n("Show all related stories");b=(0,z.D)(""+b);b=z.E(b);d+=a+z.E(z.wy({action:"show-other-responses",w:(0,z.N)(""+b),isPrimary:!0,s:"responsesStream-showOtherResponses cardChromeless u-sizeFullWidth"},c))+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"responsesStream js-responsesStreamOther"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e';return(0,z.D)(d)},$$=function(a){z.U.call(this);this.ya=
a.get("screen-request");this.fa=null;this.AO=a.get("screen-view-state");this.X=a;this.QN=!1;this.VM=this.Nc=null};z.q(q$,z.C);z.f=q$.prototype;z.f.J=function(){return""};z.f.L=function(){return"Placement"};z.f.ml=function(){return z.A(this,"items")};z.f.KI=function(a){return z.B(this,"location",a)};z.f.Pc=z.k(301);z.f.yb=function(a){return z.B(this,"index",a)};z.f.N=function(){return q$.prototype};
z.f.H={name:"Placement",fields:{items:{name:"items",g:function(){return z.RR},Z:z.X,h:function(){return 1},j:function(){return"gen.model.StreamItem"},defaultValue:function(){}},location:{name:"location",g:function(){return z.FP},h:function(){return 2},j:function(){return"gen.model.PlacementLocation"},defaultValue:function(){}},index:{name:"index",g:function(){return Number},h:function(){return 3},j:function(){return"int32"},defaultValue:function(){}}},O:{}};
z.f.Pc=z.Y(301,function(){return z.A(this,"index")});z.m(s$,z.Cj);s$.prototype.oi=function(a){var b={};z.AL(this,b,a.Gb(),"");return b};
s$.prototype.vb=function(a,b){if(!a||!b)return null;var c=new a;Object.keys(b).forEach(function(a){for(var e=a.split(/[\[\]]+/).filter(function(a){return!!a}),g=c,h;h=e.shift();){var l=g.H.ik[h];if(!l)break;var p=l.g();if(l.Z()){var r=z.ik(g,h)||[],u=e.shift(),x=Number(u);if(void 0===u||!Number.isInteger(x)||0>x)break;if(p.prototype instanceof z.Tj)l=r[x],l||(l=new p,r[x]=l),z.B(g,h,r),g=l;else{if(void 0!==e.shift())break;p=QCa(b[a],l);r[x]=p;z.B(g,h,r)}}else if(p.prototype instanceof z.Tj)r=z.ik(g,
h),r||(r=new p,z.B(g,h,r)),g=r;else{if(void 0!==e.shift())break;p=QCa(b[a],l);z.B(g,h,p)}}});return c};z.q(t$,z.Ak);z.f=t$.prototype;z.f.J=function(){return""};z.f.L=function(){return""};z.f.pH=z.k(460);z.f.N=function(){return t$.prototype};z.f.H={name:"PlacementsResponse",fields:{placements:{name:"placements",g:function(){return q$},Z:z.X,h:function(){return 1},j:function(){return"gen.model.Placement"},defaultValue:function(){}}},O:{}};z.q(v$,z.C);v$.prototype.J=function(){return""};
v$.prototype.L=function(){return""};v$.prototype.N=function(){return v$.prototype};v$.prototype.H={name:"PlacementsRequestQuery",fields:{requestContext:{name:"requestContext",g:function(){return z.BF},h:function(){return 1},j:function(){return"PlacementsRequestContext"},defaultValue:function(){}},slots:{name:"slots",g:function(){return z.DF},Z:z.X,h:function(){return 2},j:function(){return"PlacementSlot"},defaultValue:function(){}}},O:{}};
z.r1.prototype.JI=z.Y(472,function(a){a!=this.vE&&this.Va&&(this.Va.jg.contentEditable=a);this.vE=a});z.ZL.prototype.$P=z.Y(464,function(a){a=w$(a);if(!a)return null;a=x$(a)&&x$(a).ol();return a?(a=a.Fb())&&a.length?a[0].getName():null:null});t$.prototype.pH=z.Y(460,function(){return z.A(this,"placements")});
z.BL.prototype.pH=z.Y(459,function(a,b){var c=this;a=TCa(UCa(new v$,a),b);a=(new s$).oi(a);var d=this.o.F(z.rla,{},a);return z.CL(this,d,function(){return z.t(c.R.get(d,{background:!0}),function(a){a=c.ha.lb(t$,a);c.aa.nb(a);return a})})});z.kG.prototype.nJ=z.Y(440,function(a){this.Yk=a;return this});z.EM.prototype.nJ=z.Y(439,function(a){this.Yk=a;return this});z.Uw.prototype.Fm=z.Y(327,function(){return z.A(this,"note")});z.uL.prototype.Fm=z.Y(326,function(a){return this.gb("Note",a)});
z.ss.prototype.Et=z.Y(325,function(){return z.A(this,"replyId")});z.Uw.prototype.Et=z.Y(324,function(){return z.A(this,"replyId")});z.qs.prototype.qu=z.Y(323,function(a){return z.B(this,"highlight",a)});z.qs.prototype.fH=z.Y(322,function(){return z.A(this,"highlight")});z.qs.prototype.nr=z.Y(321,function(a){return z.B(this,"author",a)});z.ss.prototype.nr=z.Y(320,function(a){return z.B(this,"author",a)});z.qs.prototype.dB=z.Y(319,function(){return z.A(this,"author")});
z.ss.prototype.dB=z.Y(318,function(){return z.A(this,"author")});z.qs.prototype.Rw=z.Y(317,function(){return z.A(this,"highlightId")});z.qs.prototype.Mx=z.Y(316,function(a){return z.B(this,"authorId",a)});z.ss.prototype.Mx=z.Y(315,function(a){return z.B(this,"authorId",a)});z.qs.prototype.vu=z.Y(314,function(a){return z.B(this,"state",a)});z.ss.prototype.vu=z.Y(313,function(a){return z.B(this,"state",a)});z.Xw.prototype.vu=z.Y(312,function(a){return z.B(this,"state",a)});
z.qs.prototype.gf=z.Y(311,function(){return z.A(this,"noteId")});z.ss.prototype.gf=z.Y(310,function(){return z.A(this,"noteId")});z.Uw.prototype.gf=z.Y(309,function(){return z.A(this,"noteId")});z.Qk.prototype.qH=z.Y(117,function(){return z.A(this,"point")});z$.prototype.qH=function(){var a=window.document.body;return z.og(a,this.pg.node)?this.pg:this.Ki&&z.og(a,this.Ki)?z.Sv(this.TE,this.Ki):this.Ad&&(a=z.kp(this.I8,this.Ad))?z.Sv(this.TE,a):null};z.q(A$,z.Pg);
A$.prototype.bC=function(){if(!this.fi)return null;var a=this.fi.qH();if(!a)return null;var b=this.Kj.qH();return b?z.Uh(a.node,a.offset,b.node,b.offset):null};z.q(B$,z.U);z.f=B$.prototype;z.f.pi=function(){return this.Vk.pi()};
z.f.V=function(){B$.U.V.call(this);z.Bw(this,this.tL,"data-redirect-type-quote",this.Laa,this);this.qa(this.ld,"click",this.bs,this);z.EI(this.Ga)&&z.ov()&&this.qa(this.ld,"mouseover",this.u9,this);this.Ga.Ma().Eq()&&!this.Ga.Qc()&&z.v(this.od.load(this.Ga.ua()),z.T);var a=this.pi();a&&(z.Bw(this,a,"quote",this.p9,this),z.Bw(this,a,"quote-respond",this.q9,this),z.Bw(this,a,"show",this.sO,this),z.Bw(this,a,"hide",this.gba,this))};
z.f.Laa=function(a){var b=z.rI(this.Vk,this.pi().Rs);b&&(a.url=new z.qd(this.o.F(z.ZO,{postId:this.Ga.ua()},{paragraphs:JSON.stringify([b.Lt.vb().Gb()]),startOffset:b.start,endOffset:b.end})))};z.f.bs=function(a){z.gp(a.target,function(a){if(a===this.ld)return!0;var c=z.QE(a);if(3==c)return!0;if(7==c){if(c=jDa(this,a))if(C$(this,c),z.ov())E$(this,c);else{var d=new z.WF;hDa(this,c,a,d)}return!0}return!1}.bind(this))};
z.f.u9=function(a){z.gp(a.target,function(a){if(a===this.ld)return!0;var c=z.QE(a);if(3==c)return!0;if(7==c){c=z.xi();if(!(c&&!c.isCollapsed()||this.pi()&&this.pi().vk())&&(c=jDa(this,a))){var d=this.ld.querySelector('.markup--quote[name~\x3d"'+c.Wg()+'"]');a=new z.YF(a,100);hDa(this,c,d,a);C$(this,c)}return!0}return!1}.bind(this))};
z.f.sO=function(){var a=z.xi();a&&!a.isCollapsed()&&C$(this,null);z.EI(this.Ga)&&(a=z.rI(this.Vk,this.pi().Rs))&&(a=z.dI(this.od,a.Lt,a.start,a.end),z.gd(this.pi().pa().querySelector(".js-highlightMenuQuoteButton"),"is-active",!!a))};z.f.gba=function(){this.lm&&C$(this,null)};
z.f.p9=function(){if(z.EI(this.Ga)){var a=z.lI(this.pi());if(a){var b=a.range,c=a.dka,d=z.bd(this.pi().pa().querySelector(".js-highlightMenuQuoteButton"),"is-active"),a=z.rI(this.Vk,b);z.v(z.t(this.od.toggle(a.Lt,a.start,a.end,!c),function(a){z.cW();d?z.nI(this.pi()):E$(this,a);var b=c?"selection_menu":"quote_click_menu";F$(this,a.Wg(),!d,b)},this),z.T)}}};
z.f.q9=function(){if(z.EI(this.Ga)&&z.y.supportsEdit){var a=z.lI(this.pi());if(a){var b=z.rI(this.Vk,a.range);z.v(z.t(this.od.create(b.Lt,b.start,b.end,1,!0),function(a){F$(this,a.Wg(),!0,"selection_menu_quote_respond");this.ba("quote-respond",a,b.Lt.name)},this),z.T)}}};
z.f.B9=function(a){var b=this.lm,c=D$(this,b),d=b.xc(),e=b.rd(),b=a.query(".js-quoteAttributions-pileOn"),g=z.bd(b,"is-active");z.v(z.t(this.od.toggle(c,d,e,!0),function(b){var l=a.query(".js-quoteAttributions-pileOn");z.hd(l,"is-active");if(l=z.eI(this.od,c,d,e)){var p=gDa(this,l),r=a.query(".js-quoteAttributions-info");z.S(r,cDa,p)}else a.Qb();!g&&z.ov()&&(a.Qb(),E$(this,l));l=z.ov()?"quote_hover":"quote_click_mobile";F$(this,b.Wg(),!g,l)},this),z.T)};
z.f.C9=function(){if(z.EI(this.Ga)&&z.y.supportsEdit){var a=D$(this,this.lm),b=this.lm.xc(),c=this.lm.rd();z.v(z.t(this.od.create(a,b,c,1,!0),function(b){F$(this,b.Wg(),!0,"quote_respond");this.ba("quote-respond",b,a.name)},this),z.T)}};z.f.D9=function(){var a=lDa(this,this.lm);a&&z.uI(this.Vk,a)};
z.f.lY=function(){var a=new A$(this.ld),b=this.od.Pp,c=Object.keys(b).concat(this.jV);z.Va(c);c.forEach(function(a){var c=b[a]||[],g=this.Ga;if(g=(a=g.ld&&z.kp(g.ld,a))&&this.Ga.Vg(a))bDa(g,c),a.innerHTML=z.hs(g,z.y,z.BI(this.Ga)),z.TM(this.qda,a)},this);this.jV=Object.keys(b);(a=a.restore())&&a.select()};z.q(G$,z.yw);z.f=G$.prototype;z.f.load=function(a){if(!z.Am())return z.Rc([]);this.Fa=a;this.Rl||(this.Rl=z.v(z.t(this.em.get(this.o.F(z.tka,{postId:a}),{background:!0}),this.oda,this),z.T));return this.Rl.ic()};
z.f.Sm=function(){return this.hV};z.f.Zw=function(){return this.MX};z.f.fH=function(a){return this.kW[a]||null};z.f.Fm=function(a,b){return z.IT(H$(this,b),a)};z.f.qu=function(a,b){this.kW[a]=b};z.f.ua=function(){return this.Fa};
z.f.oda=function(a){var b=a.references.User;this.MX=a.post.visibility;var c=a.value;if(c)for(var d=0;d<c.length;d++){var e=c[d];if("HIDDEN"!=e.state){var g=e.replies,h=b;if(g)for(var l=0;l<g.length;l++){var p=g[l],r=p.authorId||null;p.author=r&&h[r]||null}g=e.anchor;h=e.authorId||null;e.author=h&&b[h]||null;g=H$(this,g);e=z.rs(e);g.add(z.FH(this.aa,e))}}if(a=a.highlights)for(b=0;b<a.length;b++)this.qu(a[b].id,z.Ck.vb(z.us,a[b]));this.hV=!0};z.m(K$,z.U);K$.prototype.V=function(){var a=this;z.U.prototype.V.call(this);z.t(this.ya.pH(this.xF,this.fda),function(b){b.placements&&b.placements.forEach(a.j$,a)})};
K$.prototype.j$=function(a){if(this.isActive()){var b=null;switch(a.location){case 1:b=this.Aa.query(".js-postFooterPlacements");if(!b)break;z.S(b,z.IV,{items:a.items,context:9});break;case 2:b=this.Aa.query(".js-readNextMetabarRight");if(!b)break;z.S(b,z.IV,{items:a.items,context:2});break;case 6:(b=this.Aa.query(".js-postPromotionWrapper"))&&z.S(b,z.IV,{items:a.items,context:2})}b&&pDa(this,b)}};z.m(L$,z.U);L$.prototype.Gd=function(a){this.fa=a};L$.prototype.V=function(){var a=this;this.W()?(z.U.prototype.V.call(this),z.v(z.t(XCa(this.ya,this.fa.Sa()),function(b){z.S(a.W(),qDa,{items:z.bI(b.Pd),context:9});var c=a.query(".js-relatedReadsStream");b=new z.aY(a.X,b.Pd);b.Na(c);b.Wf(9);a.track(b)}),z.T)):z.T("Attempted to initialize RelatedReadsStreamControl without root element.")};rDa.prototype.HG=function(a,b,c){return new B$(a,b,c)};sDa.prototype.get=function(a){return M$(this,a)};z.q(N$,z.r1);z.f=N$.prototype;z.f.eA=!1;z.f.uv="";z.f.fA=0;z.f.Um=z.X;z.f.gf=function(){return this.EM};z.f.save=function(){this.Ha().length<=this.Rj&&this.Js()};z.f.Qa=function(){(0,window.clearTimeout)(this.fA);N$.U.Qa.call(this)};z.f.V=function(){function a(a){a.stopPropagation()}N$.U.V.call(this);this.uv=this.Ha();this.Zc(this.uv);this.Zs(13,this.IM,this);this.Zs(27,this.JM,this);this.Va.qa("blur",this.HM,!1,this);var b=this.Va.pa();z.Dv(b,"keydown",a);z.Dv(b,"keyup",a);z.Dv(b,"keypress",a)};
z.f.lS=function(a){return a};z.f.Js=function(){if(this.isEnabled()){var a=this.Ha().trim();if(a){this.JI(!1);var b=this.p0(),a=this.o0(a);this.ba("saving",a);z.Hc(z.v(z.t(this.em.post(b,a.Gb()),this.Aba,this),this.yba.bind(this,a)),this.JI.bind(this,!0))}}};z.f.Aba=function(a){this.ba("save",this.lS(a.value))};z.f.yba=function(a,b){this.ba("fail",a);this.ga.error(vDa());z.T(b)};z.f.IM=function(a){if(this.bq&&this.bq.Wm())return!1;a.shiftKey||(a.preventDefault(),this.save());return!0};
z.f.JM=function(a){if(this.bq&&this.bq.Wm())return!1;a.preventDefault();this.Zc(this.uv);this.ba("cancel");return!1};z.f.HM=function(){this.eA&&(this.Ha().length>=this.Rj?(0,window.confirm)(this.r0())?(this.Zc(this.uv),this.ba("cancel")):this.focus():this.fA=(0,window.setTimeout)(this.Js.bind(this),100))};z.q(O$,N$);z.f=O$.prototype;z.f.cK=null;z.f.IU=null;z.f.dK=null;z.f.$h=null;z.f.JL=null;z.f.IL=null;z.f.jW=null;z.f.qu=function(a){this.$h=a;this.JL=a.startIndex;this.IL=a.endIndex;this.jW=a.content;return this};z.f.r0=function(){var a=z.n("Your note is too long; do you want to abandon your changes?");return(0,z.D)(""+a)};z.f.lS=function(a){var b=z.kv();a=z.rs(a).nr(b).Mx(b.Wa());this.$h&&a.Rw()&&this.he.qu(a.Rw(),this.$h);var b=this.he,c;c=z.FH(b.aa,a);H$(b,c.Oc()).add(c);return a};
z.f.p0=function(){return this.gf()?this.o.F(z.uka,{postId:this.Fa,noteId:this.gf()}):this.o.F(z.ska,{postId:this.Fa})};z.f.o0=function(a){var b=z.kv();a=(new z.qs({content:a,anchor:this.cK,anchorContent:this.IU,anchorImage:this.dK?this.dK.Gb():null,replies:[],createdAt:Date.now()})).nr(b);null!=this.JL&&null!=this.IL&&(b=new z.us({anchor:this.cK,startIndex:this.JL,endIndex:this.IL,content:this.jW}),a.qu(b));return a};z.q(P$,N$);P$.prototype.r0=function(){var a=z.n("Your reply is too long; do you want to abandon your changes?");return(0,z.D)(""+a)};P$.prototype.lS=function(a){var b=z.kv();a=z.ts(a).nr(b).Mx(b.Wa());z.A(this.he.Fm(a.gf(),this.Ad),"replies").push(a);return a};P$.prototype.p0=function(){return this.hY?this.o.F(z.xka,{postId:this.Fa,noteId:this.gf(),replyId:this.hY}):this.o.F(z.wka,{postId:this.Fa,noteId:this.gf()})};
P$.prototype.o0=function(a){var b=z.kv();return(new z.ss({replyId:"",postId:this.Fa,noteId:this.gf(),content:a,createdAt:Date.now()})).nr(b)};z.q(R$,z.U);z.f=R$.prototype;
z.f.V=function(){R$.U.V.call(this);z.V(this.W()).D("show-note-editor",this.TN,this).D("hide-note-editor",this.FL.bind(this,!0)).D("show-reply-editor",this.wfa,this).D("hide-reply-editor",this.Z9,this).D("save-note",this.rea,this).D("save-reply",this.tea,this).D("highlight-quote",this.c$,this).D("dismiss-note",this.mV.bind(this,!0),this).D("delete-note",this.mV.bind(this,!1),this).D("delete-reply",this.b8,this).D("previous-highlight-tip",this.mda,this).D("next-highlight-tip",this.oaa,this);JDa(this);
this.vh&&r$(this.vh)&&(IDa(this),z.Bw(this,r$(this.vh),"add",this.xba,this));if(this.qN&&this.vW&&this.xW){var a=this.query(".js-inlineNewPostControl"),b=this.qN,c=this.Ga.ua(),d=new z.JX(this.X);d.Ox("web-inline-quote-responses");d.Na(a);d.Jy=!0;d.QK=!0;d.OK=!0;d.UF=dDa;d.js=b;d.nC(c);z.KX(d,!0);this.Nc=d;this.Nc.S();a=T$(this.Tz);this.ba("set-active-highlight",this.Ad,a)}this.$h&&(this.TN(),this.xe&&this.xe.focus());U$(this,0)};
z.f.ia=function(){this.wn&&this.wn.BP();(this.$h||this.Tz)&&this.ba("reset-highlight",this.Ad,null);R$.U.ia.call(this)};z.f.Qa=function(){z.ux(this.W());z.ig(this.W());z.Md(this.Nc);z.Md(this.xe);z.Md(this.wn);z.Nd(z.cb(this.di));this.wn=this.di=this.xe=this.Nc=null;R$.U.Qa.call(this)};z.f.Mm=function(){if(this.xe&&this.xe.Ha())return!0;for(var a=z.cb(this.di),b=0;b<a.length;b++)if(a[b]&&a[b].Ha())return!0;return this.Nc&&!this.Nc.isDismissable()?!0:!1};
z.f.uK=function(){var a=[],b=[],c=[],d=this.xv&&(this.$h||this.Tz);d||(this.rs?(a=this.od?u$(this.od,this.rs.quotes):[],b=this.rs.notes,c=this.rs.responses):(b=this.he?z.bI(H$(this.he,this.Ad)):[],this.EM||(this.od?(a=this.od,a=u$(a,a.Pp[this.Ad]||[])):a=[],c=this.vh?y$(this.vh,this.Ad):[])));return z.lv(FDa,{post:this.Ga.Ma(),quotes:a,notes:b,responses:c,CT:!!this.qN,UI:d,uC:this.xv,$x:this.bZ,Vka:z.DI(this.Ga)})};
z.f.xba=function(){var a=this.query(".js-blockGroupPosts"),b=z.lv(EDa,{responses:y$(this.vh,this.Ad)});z.jg(b,a);IDa(this)};
z.f.TN=function(){if(this.xv){if(!this.xe){var a=this.query(".js-noteEditor"),b=String(z.Q(CDa)),a=this.xe=new O$(this.X,a,this.Ga.ua(),null,b),b=this.Ad,c=this.Ga.Vg(this.Qd.get(this.Ad)),d=c.la(),c=4==c.type?c.yd():null;a.cK=b;a.IU=d;a.dK=c;(a=this.$h)&&this.xe.qu(a);z.Bw(this,this.xe,"saving",this.$ba,this);z.Bw(this,this.xe,"fail",this.eba,this);z.Bw(this,this.xe,"save",this.Vba,this)}z.w(this.query(".js-noteActions"),"is-noteEditorVisible");this.xe&&this.xe.focus()}};
z.f.rea=function(){this.xe&&this.xe.save()};z.f.$ba=function(a){this.xe.Zc("");var b=this.query(".js-notesList");a={note:a,post:this.Ga.Ma(),UI:this.xv,uC:this.xv};a=z.lv(Q$,a);b.appendChild(a);z.ed(b,"is-empty");JDa(this);this.FL()};z.f.Vba=function(a){var b=this.query(".js-notesList").lastChild;a=a.gf();z.w(b,"js-note-"+a);b.setAttribute("data-note-id",a);(b=b.querySelector(".js-deleteNote"))&&b.setAttribute("data-action-value",a)};
z.f.eba=function(){var a=this.query(".js-notesList");a.removeChild(a.lastChild);z.w(a,"is-empty");this.TN()};z.f.FL=function(a){a?this.ba("close"):this.xe&&(this.xe.Ha()&&this.xe.Zc(""),z.ed(this.query(".js-noteActions"),"is-noteEditorVisible"))};z.f.wfa=function(a){(a=S$(a.target))&&this.xv&&KDa(this,a)};z.f.tea=function(a){a=S$(a.target);(a=this.di[a])&&a.save()};
z.f.aca=function(a){var b=a.gf();this.di[b]&&this.di[b].Zc("");var c=this.he.Fm(b,this.Ad).author.userId==a.author.userId,d=this.query(".js-note-"+a.gf()+" .js-repliesList");a={note:a,post:this.Ga.Ma(),y1:c};a=z.lv(Q$,a);d.appendChild(a);z.ed(d,"is-empty");LDa(this,b)};z.f.Wba=function(a){var b=this.query(".js-note-"+a.gf()).querySelector(".js-repliesList").lastChild;a=a.Et();z.w(b,"js-reply-"+a);(b=b.querySelector(".js-deleteNote"))&&b.setAttribute("data-action-value",a)};
z.f.fba=function(a){var b=this.query(".js-note-"+a.gf()+" .js-repliesList");b.removeChild(b.lastChild);z.w(b,"is-empty");KDa(this,a.gf())};z.f.Z9=function(a){(a=S$(a.target))&&LDa(this,a)};z.f.c$=function(a){a=a.target;var b=a.getAttribute("data-quote-creator-id"),c=M$(this.Qd,this.Ad);c&&(this.wn&&this.wn.BP(),this.wn=NDa(this,c,a,function(){MDa(this,b,!1);z.Md(this.wn);this.wn=null}),MDa(this,b,!0))};
z.f.b$=function(a){var b=M$(this.Qd,this.Ad);(a=this.he.Fm(a.target.getAttribute("data-note-id"),this.Ad))&&b&&(b=(b=a.Rw())?this.he.fH(b):null,this.ba("set-active-highlight",this.Ad,b))};z.f.d$=function(a){var b=M$(this.Qd,this.Ad),c;c=this.vh;a=a.target.getAttribute("data-post-id");c=r$(c)?z.IT(r$(c),a):null;b&&c&&(b=w$(c))&&(b=x$(b)&&x$(b).ol())&&(c=b.Fb())&&c.length&&(b=T$(b),this.ba("set-active-highlight",this.Ad,b))};
z.f.rO=function(){var a=null;this.Tz&&(a=T$(this.Tz));this.$h&&(a=this.$h);this.ba("reset-highlight",this.Ad,a)};
z.f.mV=function(a,b){b=b.value;var c=this.he.Fm(b,this.Ad),d=this.query(".js-note-"+b);if(c&&d){z.mp(d);this.rO();this.ub(".js-note-item").every(function(a){return z.bd(a,"u-hide")})&&this.FL(!0);var e=I$(this.he,c,"HIDDEN");z.v(e.dj,function(b){this.ea.S(a?wDa():xDa(),"error");e.cC();z.np(d);(400>b.status||499<b.status)&&I$(this.he,c,"NEW")},this);z.t(this.ea.S(a?zDa():ADa(),{type:"success",ay:!0}),function(){this.ea.Qb();e.cC();I$(this.he,c,"NEW");z.np(d)},this)}};
z.f.b8=function(a){var b=a.value,c=this.query(".js-reply-"+b),d=S$(a.target);if(d&&c){z.mp(c);var e=J$(this.he,b,d,this.Ga.ua(),this.Ad,"HIDDEN");z.v(e.dj,function(){this.ea.S(yDa(),"error");e.cC();z.np(c);J$(this.he,b,d,this.Ga.ua(),this.Ad,"")},this);z.t(this.ea.S(BDa(),{type:"success",ay:!0}),function(){this.ea.Qb();e.cC();J$(this.he,b,d,this.Ga.ua(),this.Ad,"");z.np(c)},this)}};z.f.mda=function(){U$(this,this.kE-1)};z.f.oaa=function(){U$(this,this.kE+1)};z.q(V$,z.U);z.f=V$.prototype;z.f.V=function(){V$.U.V.call(this);var a=[];z.DI(this.Ga)&&a.push(this.he.load(this.Fa));this.BW||(a.push(this.od.load(this.Fa)),a.push(this.vh.load(this.Fa)));this.Wr=z.t(z.t(z.t(z.NF(a),function(){this.Wr=null},this),this.AI,this),this.j7,this);z.Bw(this,this.$a,"resize-end",this.We,this)};z.f.ia=function(){this.Wr&&this.Wr.cancel();V$.U.ia.call(this)};z.f.Qa=function(){this.Wr=null;V$.U.Qa.call(this)};z.f.AI=function(){tDa(this.Qd,function(a,b){W$(this,b)},this)};
z.f.We=function(){tDa(this.Qd,function(a,b){UDa(this,b)},this)};z.f.j7=function(){var a=this.od.dm;z.Bw(this,a,"add",this.wX,this);z.Bw(this,a,"remove",this.wX,this);(a=r$(this.vh))&&z.Bw(this,a,"add",this.Sba,this)};z.f.wX=function(a){ODa(this,Object.keys(z.hI(this.od,a instanceof Array?a:[a])))};z.f.Sba=function(a){ODa(this,(a instanceof Array?a:[a]).map(this.vh.$P,this.vh))};z.f.uK=function(a){var b=window.document.createElement("div");b.className="notesMarkers";a.appendChild(b);return b};
z.f.sz=function(a,b){z.lb(a,{startIndex:Math.min(a.startIndex,b.startIndex),endIndex:Math.max(a.endIndex,b.endIndex),notes:a.notes.concat(b.notes),quotes:a.quotes.concat(b.quotes),responses:a.responses.concat(b.responses)})};z.q(X$,z.U);z.f=X$.prototype;
z.f.V=function(){X$.U.V.call(this);this.qa(this.Aa.W(),"click",this.V$,this,!0);z.V(this.qz).D("select-anchor",this.bca,this);var a=this.Ga.Ma();if(a.Eq()&&!this.Ga.Qc()){var b=z.jm(a),b=2==a.visibility&&b&&!z.A(b.Ih(),"memberOfMembershipPlanId");a.allowResponses&&!b&&z.v(this.vh.load(this.Ga.ua(),"best"),z.T);z.v(this.od.load(this.Ga.ua()),z.T)}a.Ih().ZG()&&(this.RE=z.t(this.he.load(this.Ga.ua()),this.Bba,this));this.nM&&Z$(this);z.Bw(this,this.Oa,"historyUpdate",function(){Z$(this,z.QI())},this);
this.Td&&z.Bw(this,this.Td,"highlight",this.zba,this)};z.f.Qa=function(){z.Md(this.Zf);this.Zf=null;z.Md(this.Gj);this.Gj=null;this.qz&&z.V(this.qz).clear("select-anchor");this.RE&&this.RE.cancel();this.RE=null;X$.U.Qa.call(this)};z.f.Zka=function(a,b){Y$(this,b,null,null,a)};z.f.Gma=function(){this.Zf&&this.Zf.We()};z.f.Mm=function(){if(!this.Gj)return!1;var a=this.Gj.Ha();return a?a.Mm():!1};z.f.wba=function(a){a.subscribe("add",this.jZ,this);a.subscribe("remove",this.jZ,this)};
z.f.jZ=function(a){(z.ea(a)?a:[a]).forEach(function(a){W$(this.Zf,a.Oc())},this)};z.f.Bba=function(){var a=(0,z.za)();this.RE=null;Z$(this,z.QI());this.qa(this.Ij,z.ON,this.QM,this);z.BC("notes.renderMarkers",(0,z.za)()-a)};z.f.QM=function(a){(a=a.target.getAttribute("name"))&&M$(this.Qd,a)&&UDa(this.Zf,a)};z.f.zba=function(){if(this.Td){var a=$Da(this,this.Td.Rs);z.nI(this.Td);a&&(a=a.highlight,this.tY(a.anchor,a),Y$(this,a.anchor,a))}};
z.f.V$=function(a){if(this.Gj){var b=a.target;if(!z.og(this.Gj.W(),b)){var c=this.Gj.Ha(),d;if(!(d=!c)){a:if(c.xe&&c.xe.Ha())c=!0;else{d=z.cb(c.di);for(var e=0;e<d.length;e++)if(d[e]&&d[e].Ha()){c=!0;break a}c=c.Nc&&!c.Nc.bh()?!0:!1}d=!c}d&&(c=this.Gj&&this.Gj.cl,d="select-anchor"==b.getAttribute("data-action"),this.yN(),c&&d&&z.og(c,b)&&a.stopPropagation())}}};
z.f.Yk=function(a){if(!(767>=window.innerWidth)){var b=a.cl,c=z.Pv(b);a.hj();a=a.W();var d=z.Pv(a),e=window.innerHeight,g=window.innerWidth,h=this.Aa.query(".js-metabar"),l=0;h&&(l=z.Pv(h).height);d.height>=e-l?z.w(a,"floating--sidebar"):(z.Kv(b),b=c.top+d.height>=e?z.Lv().top+e-d.height-10:z.Kv(b),c=z.Pv(this.qz).left+10,c+d.width>=g&&(c=g-d.width-10),a.style.top=b+"px",a.style.left=c+"px")}};z.f.yN=function(){z.Md(this.Gj);this.Gj=null};
z.f.bca=function(a){var b=z.gp(a.target,function(a){return z.bd(a,"js-paragraphControl")},this.FX),b=VDa(this.Zf,a.value,b);Y$(this,a.value,null,null,null,b)};z.f.tY=function(a,b){if(this.Ga.Qc()){var c=z.xi();this.CF=(c=c&&uDa(this.Qd,z.Tg(c)))&&new A$(c)}ZDa(this,a,b)};z.f.bea=function(a,b){ZDa(this,a,b);this.Ga.Qc()&&this.CF&&(a=this.CF.restore())&&a.select();this.CF=null};
z.f.Ms=function(a){if(this.Qd&&(a=M$(this.Qd,a))){a=Math.max(z.Kv(a),0);var b=window.document.body;this.Hj&&this.Hj.cancel();this.Hj=new z.OF(b,"scrollTop",600,a)}};aEa.prototype.HG=function(a,b,c){return new X$(a,b,c)};z.m($$,z.U);z.f=$$.prototype;z.f.Gd=function(a){this.fa=a};z.f.Xla=function(a){this.QN=a};z.f.V=function(){this.W()?(z.U.prototype.V.call(this),z.V(this.W()).D("show-other-responses",this.IY,this),z.S(this.W(),bEa,{post:this.fa}),this.fa.Eq()&&z.v(z.t(z.t(z.t(WCa(this.ya,this.fa.Sa(),"best"),this.fY.bind(this,"best")),this.Nda,this),function(){this.AO.cT&&this.IY()},this),z.T)):z.T("Attempted to initialize ResponsesStreamControl without root element.")};
z.f.ia=function(){z.V(this.W()).clear("show-other-responses");z.U.prototype.ia.call(this)};z.f.fY=function(a,b){this.isActive()&&(b=b.Pd,"best"==a?(a=this.query(".js-responsesStream"),z.Bw(this,b,"add",this.bX.bind(this,b)),this.bX(b)):a=this.query(".js-responsesStreamOther"),b&&(z.Cm()||0<b.wd())&&a&&(z.S(a,z.IV,{items:z.bI(b),context:2}),b=new z.aY(this.X,b),b.Na(a),b.Wf(2),this.track(b),z.np(this.query(".js-responsesStreamWrapper"))))};
z.f.Nda=function(){var a=this.query(".js-inlineNewPostControl"),b=this.query(".js-responsesLoggedOutPrompt");z.Cm()?a?(this.Nc=z.KX(VCa((new z.JX(this.X)).Ox("web-inline-post-response").nC(this.fa.Sa()),z.Q(z.kq,{post:this.fa,DI:!0})),this.QN).Na(a),this.track(this.Nc)):b&&this.QN&&(a=z.Jv(b),b=z.Kv(b),z.Hv(a,0,b)):b&&z.w(b,"u-hide")};
z.f.IY=function(){this.VM||(this.VM=z.Hc(z.t(z.t(WCa(this.ya,this.fa.Sa(),"other"),this.fY.bind(this,"other")),function(){z.mp(this.query(".js-showOtherResponses"));this.AO.cT=!0},this),function(){this.VM=null},this))};z.f.bX=function(a){var b=a.Ti;(b=b&&b.next&&"other"==b.next.filter)&&!this.AO.cT&&(z.np(this.query(".js-responsesStreamWrapper")),z.np(this.query(".js-showOtherResponses")));b||0!=a.wd()||!z.Dm(z.y).enable_response_experiment_c&&!z.Dm(z.y).enable_response_experiment_d||z.np(this.query(".js-noOtherResponses"))};
z.f.nt=function(){this.Nc&&(z.LW(this.Nc.W(),new z.Di(60,0,200,0)),this.Nc.nt())};var cEa=z.YB,dEa=cEa.Ba();dEa.scope("screen").add("quotes",rDa).add("quote-responses",aEa).add("responses-stream-control",$$).add("notes-data",G$).add("related-reads-stream-control",L$);z.KT(dEa.scope("app"),"PlacementsControl",K$);z.LT(cEa,"notes");}).call(this, _mdm);
